### ISSUE TITLE
Documentation Structure Entmoot

### ISSUE THREAD

**Issue by chrisdickinson** [nodeconf/Adventure-UNCONF#10]
I'd like to see Node's documentation get better. While we currently have fairly complete and well-written API reference docs, we're missing a lot of other docs: tutorials, topic guides, internal documentation, navigation, policies, etc. One clear sign that things could be better is that we're running out of places to put this info – some of it's going into project wikis, some of it is being shoved into ALLCAPS.md files at project root. Often the topics these docs touch on cross over – CONTRIBUTING.md + COLLABORATORS.md comes to mind! We need good docs, and the first step in that is having a good structure – one that can address our information storage needs for the future.

I've been a part of several documentation efforts over the years – there's a lot of enthusiasm for writing good documentation, but that enthusiasm is often hard to direct. I'd like to propose some specific goals for this meeting:
1. At the end of the meeting, we should have a proposed documentation structure. This will be in the form of directories (with assumed index landing pages.)
2. We should agree on a brief set of editorial standards to hold new documentation to for all new docs.

We want to have _just_ enough agreement on direction that we can get ourselves out of the way and let everyone pitch in. If we reach these goals, we can propose the new structure on the Node issue tracker, and start dividing up the work of creating this documentation at that point.

Before the meeting:
- Please have read @jacobian's excellent [series](https://jacobian.org/writing/what-to-write/) of [posts](https://jacobian.org/writing/technical-style/) on [technical documentation](https://jacobian.org/writing/editors/) and editing.
- Post on this issue any topics that you would like to have documented – ones that you feel are missing!
- Also suggest other talks/posts you'd like everyone to review before meeting up.
- Other talks and posts might be added to this list before the conf – check back in!

/cc @qard @fishrock123 @mikeal

**Comment by Fishrock123** [comment]
:+1:

**Comment by Qard** [comment]
:+1: 

I'm really interested in improving contributor docs. The [CONTRIBUTING.md](https://github.com/nodejs/io.js/blob/master/CONTRIBUTING.md) and [COLLABORATOR_GUIDE.md](https://github.com/nodejs/io.js/blob/master/COLLABORATOR_GUIDE.md) we currently have do a great job of covering the process, but don't really get into how the actual code works.

Some aspects of the code already have documentation in one form or another _somewhere_ but people may not be aware of them. I'll compile a list of a few things here, but we should work toward integrating these somehow into the contributor introduction/reference docs.
- v8
  - [generated API docs for various versions](https://github.com/thlorenz/v8-perf#documentation)
    - It might be good to have somewhere with generated docs matched to node/io.js versions they are relevant to.
  - [more generated API docs](https://v8docs.nodesource.com/)
  - [performance notes](https://github.com/thlorenz/v8-perf#readme)
  - [IRHydra2](http://mrale.ph/irhydra/2/)
    - Should probably explain what IR is too...
- libuv
  - [docs](http://docs.libuv.org/)
  - [book](http://nikhilm.github.io/uvbook/)
  - [rough type docs](https://github.com/thlorenz/libuv-dox)
- http_parser
  - [readme](https://github.com/nodejs/io.js/tree/master/deps/http_parser#readme)
- openssl
  - ???
- zlib
  - ???
- tracing
  - [lttng](http://lttng.org/docs/)
  - dtrace ???
  - ETW ???
- quick explanation of test suite directory structure ???
- code style ???
  - We have linting, but it'd be good to understand style before you start writing stuff
- [release process](https://github.com/nodejs/io.js/blob/master/doc/releases.md)

**Comment by danfinlay** [comment]
I think even the API docs could use a little love.  For example, if you look up the `http.createServer` method, you get told what event triggers the callback, but there's no link to that event, and the average user is going to have to `command-F` to find what that means, before they get to the `IncomingMessage` and `responseObject` definitions.
