### ISSUE TITLE
TSC Panel

### ISSUE THREAD

**Issue by Fishrock123** [nodeconf/Adventure-UNCONF#11]
I'm not entirely sure who is coming, but I figure there might be a bunch of us there and if people are interested / willing we could do some sort of panel / tsc meeting / etc.

It has also been suggested to me that it would be really cool if people from the TSC could do a panel like [Confessions of a jQuery Committer](https://youtu.be/Tdpn7y5nOeE) (i.e. How did we become TSC members / core people). I don't feel like any of this requires lots of prep, so...

cc @chrisdickinson / @mikeal Any idea who else from the TSC might be coming? Unfortunately I can't mention the group from here.

**Comment by mikeal** [comment]
This should be relatively easy :)
