### ISSUE TITLE
Discussion: Performance Monitoring for V8 and libuv

### ISSUE THREAD

**Issue by danielkhan** [nodeconf/Adventure-UNCONF#12]
I am currently researching ways to measure performance and detect bottlenecks in Node.js applications.

Although I've already accomplished to create simple realtime metrics using V8 profiler I am still not sure which measures are really providing value to developers and operation folks.
E.g. what do event loop timings really tell us (and is my way of measuring them valid)?

I will briefly share what I found out and I am hoping for an open discussion about which metrics are desirable, how to measure them and what could be added in future versions of Node.js. 
I would also be happy to hear the voice of some core developers on this.

**Comment by devinivy** [comment]
:+1: sounds like a great discussion.

**Comment by avidas** [comment]
+1

**Comment by DJCordhose** [comment]
:+1:

**Comment by danielkhan** [comment]
This will be turned into a workshop. See https://github.com/nodeconf/Adventure-UNCONF/issues/17
