### ISSUE TITLE
Workshop?: Containers & Virtualization Stuff

### ISSUE THREAD

**Issue by danfinlay** [nodeconf/Adventure-UNCONF#15]
I've heard a few people wrestling w/ Docker and all this fun DevOps type stuff, and I've heard a couple people who sounded fit to run such a workshop (not me, just throwing it up here for discussion).

**Comment by danfinlay** [comment]
Adam said he'd do this ;)

**Comment by avidas** [comment]
+1 would be a good workshop to have
