### ISSUE TITLE
Workshop: Performance Monitoring for Node.js - a DIY approach

### ISSUE THREAD

**Issue by danielkhan** [nodeconf/Adventure-UNCONF#17]
Whenever there is bad press about Node.js it is about performance issues it's about performance issues in production systems.
I am currently researching ways to instrument Node.js to get proper memory and CPU metrics that may help to detect bottlenecks in applications.

In this workshop we'll briefly go over some top performance problems and use an example project to apply instrumentation to it. Then we'll try to do somethings useful with the huge amount of data we get ... like creating cool sunburst charts using d3.
![1368639-express](https://cloud.githubusercontent.com/assets/2722161/8141279/8f54e598-1119-11e5-989d-7d86e473e32c.png)

**Comment by avidas** [comment]
+1
