### ISSUE TITLE
Discussion: Streams - Notes

### ISSUE THREAD

**Issue by jtemplet** [nodeconf/Adventure-UNCONF#18]
What you need for 0.10 streams - highWaterMark

**Mafintosh's Stream Modules To Fix Node.js Streams**
- pump - https://www.npmjs.com/package/pump
- Duplexify - https://www.npmjs.com/package/duplexify
- end-of-stream - https://www.npmjs.com/package/end-of-stream
- pumpify - https://www.npmjs.com/package/pumpify

**Comment by kumavis** [comment]
thanks for this!

**Comment by kumavis** [comment]
hot stuff: https://github.com/maxogden/mississippi
