### ISSUE TITLE
Workshop: ES6 features in io.js

### ISSUE THREAD

**Issue by DJCordhose** [nodeconf/Adventure-UNCONF#2]
Coding workshop on new ES6 features in io.js: https://iojs.org/en/es6.html

**Comment by mikeal** [comment]
Great idea!

**Comment by DJCordhose** [comment]
Of course, this will be based on io.js 2.x which has even more great ES6 support :)

**Comment by thefourtheye** [comment]
Please record and release the session.

**Comment by mikeal** [comment]
it's a workshop, can't reallly record it effectively as a video.

**Comment by thefourtheye** [comment]
@mikeal My bad, I didn't read it properly.

**Comment by yosuke-furukawa** [comment]
I have created ES6 workshopper, named tower-of-babel. 
https://github.com/yosuke-furukawa/tower-of-babel

BUT, these exercises are not based on io.js. If this workshop will use this, I will arrange this in iojs v2.

**Comment by DJCordhose** [comment]
Hey, @yosuke-furukawa thanks for the offer, I am afraid, we will not have enough time for the complete workshop, plus, some of the features babel supports already are not in io.js, yet...

**Comment by yosuke-furukawa** [comment]
@DJCordhose 

> some of the features babel supports already are not in io.js

Yes :( BUT I can change my exercises for io.js.
But this workshop has only 1 hour. If i squash the exercises, it is not enough time for complete. 

Do you have any idea to introduce the io.js ES6 features ??

**Comment by DJCordhose** [comment]
All I can do in an hour is to give people a feeling for ES6. We will have two small exercises, but I will still present a more or less complete overview of what is possible in io.js already. Will post a link to the git repo soon.

**Comment by DJCordhose** [comment]
I have prepared some material for the workshop now

https://github.com/DJCordhose/ecmascript-2015-iojs/tree/master/workshop

this is part of a more general thing, where we document what ES6 features work in io.js already. It is work in progress, but we already have enough material for the workshop.
