### ISSUE TITLE
Discussion: Nodeschool participation

### ISSUE THREAD

**Issue by kumavis** [nodeconf/Adventure-UNCONF#22]
notes

```
bootstrapping
- how to install node
- run tuts w/o installing, e.g. docker (download app / hosted online?)

new workshoppers
- workshop workshopper?
- css
- unix tools
    - terminal intro (ls, touch, cd)
    - bash
- regex
- synthesis (dont care about DBs, want to make a thing)
    - e.g. make a video game, make a blog
    - could be made from a couple workshops
    - look at this neat thing, I want to try to make it

etc
- workshop roulette
- hacking websites people already use? (e.g. css in tumblr, favorite all posts in twitter)
- how to balance removing complexity and not using a real dev environment
```

**Comment by kumavis** [comment]
nodeschool: http://nodeschool.io/
workshopper + docker: https://github.com/generalhenry/nodeschool-interactive
workshopper wishlist: (ideas and in-progress) https://github.com/nodeschool/workshoppers/issues + https://github.com/nodeschool/discussions/issues/181

**Comment by kumavis** [comment]
notes on workshoppers https://github.com/nodeschool/workshoppers/issues

**Comment by kumavis** [comment]
creating your own workshopper tutorial: http://lin-clark.com/blog/2014/07/01/authoring-nodejs-workshopper-lessons/

**Comment by Frijol** [comment]
These are the command line basics tutorials I wrote/use – not perfect but they work pretty well http://start.tessel.io/cmd
