### ISSUE TITLE
Nodeconf 2017 update thread

### ISSUE THREAD

**Issue by tamzinblake** [nodeconf/Adventure-UNCONF#23]
We're still setting up lines of communication, but you can watch this issue to get info about next year's NodeConf when it becomes available.

**Comment by tamzinblake** [comment]
Created https://nodeconf-adventure.slack.com for chattish discussion.

**Comment by tamzinblake** [comment]
Can email nodeconf.adventure@gmail.com for an invite (or any questions)

**Comment by tamzinblake** [comment]
Date confirmed for 2017: July 6-9

**Comment by williamkapke** [comment]
Hey @thomblake! Is this still set? I know there are a few folks that have this on their calendar. Tickets soon?

**Comment by tamzinblake** [comment]
@williamkapke I'm working on the final details that will be needed before opening up ticket sales. Expect news in the next week.

**Comment by tamzinblake** [comment]
For some values of "expect" and "week"

**Comment by tamzinblake** [comment]
Tickets now on sale: https://ti.to/nodeconf/nodeconf-adventure-2017

**Comment by tamzinblake** [comment]
This year's event is going to be cancelled. There will be a post after the postmortem with details and steps to make next year a success. Anyone who has already bought tickets will be refunded.
