### ISSUE TITLE
Date for 2017

### ISSUE THREAD

**Issue by tamzinblake** [nodeconf/Adventure-UNCONF#24]
Are there any constraints around next year's date?  Things we don't want to conflict with: Maker Faire, Burning Man.

The second weekend of June is the 8th through the 12th next year.

**Comment by tamzinblake** [comment]
Definitely won't conflict with either of those.  Anything else we should be worried about?

**Comment by dshaw** [comment]
@brycebaril shared with me that early June is before his kids are done with school. Last year he had to pull them out early.

**Comment by brycebaril** [comment]
As @dshaw said--when it's early it definitely makes it harder for those with school-age kids to attend with their families.

**Comment by tamzinblake** [comment]
Based on my limited research, it looks like most California schools usually let out the first week of June, and if we wanted to avoid pretty much all American school overlap we'd have to move to July.  If we didn't have anecdotal evidence to the contrary, I'd suspect the second week of June was pretty ideal.

@brycebaril When do your kids get out of school?

**Comment by brycebaril** [comment]
@thomblake this year they got out the week of NodeConf, I would have had to only pull them out a day early. Seattle, however, still has 3 weeks of school left including this week. It was much easier for families when it was in July--we talked to other families who chose not to go this year with school age kids due to school.

**Comment by tamzinblake** [comment]
Any issues with particular dates in July? I can't think of any. If not,
we'll just see whether it makes a difference with the venue.

**Comment by davidguttman** [comment]
4th of July weekend might be a tough one.

**Comment by tamzinblake** [comment]
4th of July is a Tuesday so I don't know what counts as that weekend if
anything.

**Comment by lyle** [comment]
My family couldn't attend due to school conflict +1 for July.

**Comment by mikeal** [comment]
We did 4th of July a few years ago and a lot of people complained that they had other obligations over that holiday :/

**Comment by tamzinblake** [comment]
I agree that 4th of July is probably no good, but I don't know what "4th of July weekend" means when the conf is on Thursday-Sunday and the 4th is a Tuesday.

**Comment by nebrius** [comment]
4th of July weekend is usually home to a lot of activities. There's a yearly campout I go to, and I think a few other Node folks go to, during that weekend, so I would be unavailable.

**Comment by tamzinblake** [comment]
If anyone knows what "4th of july weekend" means in context, I'd like to know.  That said, I'm thinking 13th-16th, but waiting to hear back from the folks about what's available.

**Comment by davidguttman** [comment]
Next year it will be the weekend before the 4th: 7/1 - 7/4.

**Comment by tamzinblake** [comment]
@mikeal How do you usually contact the WCR folks for a reservation?  I sent emails and tried calling (left a message). Not sure how long I should expect before they get back to me.

**Comment by mikeal** [comment]
@thomblake Patrick is the person to talk to, he can sometimes be a little difficult to nail down via email but he usually gets back eventually.

**Comment by tamzinblake** [comment]
Here's the email from Patrick:

```
Thank for your interest in Walker Creek Ranch Conference Center. Unfortunately, the
weekend of July 13-16 is currently unavailable. We do have availability June 29-July 2 and July 6-9.

In order to get on the calendar we would need the following preliminary information:
·         Dates of event

·         First and last meal

·         Number participating

·         Lodging needs

·         Meeting room needs


Once we have you on the calendar, next steps would include signing the contract and providing a deposit (25%).

Let me know if I can be of further assistance.
```

I was thinking July 6-9th is fine (June 29-July 2 is no good because it's apparently 4th of July weekend)

@mikeal How specific do we have to be in advance with number participating, lodging needs, and meeting room needs?

**Comment by tamzinblake** [comment]
Date confirmed, we're on the WCR calendar.

**Comment by mikeal** [comment]
Which dates are you confirmed for? I want to put this on a few calendars we use for planning in the foundation.

**Comment by tamzinblake** [comment]
July 6-9th
