### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by tamzinblake** [nodeconf/Adventure-UNCONF#26]
We should update the CoC. I'm pretty sure it's years old, and the tl;dr is a big red flag at this point.

Here's the current CoC: http://nodeconf.com/code-of-conduct.html

Here's the Node CoC: https://github.com/nodejs/node/blob/master/CODE_OF_CONDUCT.md - it's not really designed for a conference so can't be used as-is.  I'd normally be concerned about the "anti-profanity" thing but with so many small children about maybe that's not so bad.

And here's the Alterconf CoC, which is probably about as close to the state of the art on these things that you can get: http://www.alterconf.com/code-of-conduct#coc

**Comment by nebrius** [comment]
Let's...uhm...not dig into the profanity bit, there's dragons in its history.

I think the AlterConf CoC is based on the [JSConf CoC](http://jsconf.com/codeofconduct.html), so there's good lineage there from the JS Community there, so +1 from me for switching to it.

**Comment by mikeal** [comment]
Agreed, the AlterConf CoC is basically a linear improvement on the one that has been here since 2013.
