### ISSUE TITLE
Workshop: Building a fullstack io.js application

### ISSUE THREAD

**Issue by DJCordhose** [nodeconf/Adventure-UNCONF#3]
Beginners tutorial how to build a very simple application using io.js, hapi, handlebars, bootstrap, and mongoose

**Comment by mikeal** [comment]
I like this idea too but are you sure you can lead 2 workshops?

**Comment by DJCordhose** [comment]
Yes, sure. Not at the same time, though :D

Seriously, yes, I do this regularly, they are just one hour each, right?

**Comment by mikeal** [comment]
I should work on making this clearer. The workshop is an hour but each one should run 3 times in a row. That way each attendee gets a chance to go to 3 workshops without worrying about overlap. You could still do two but it would be on two separate days, and each one would run 3 times.

**Comment by DJCordhose** [comment]
Oh, that makes it clear. Would that mean if I do two, I could not participate in any workshops other people lead?

**Comment by DJCordhose** [comment]
Made up my mind. In any case I would be willing to lead both workshops...

**Comment by mikeal** [comment]
> Oh, that makes it clear. Would that mean if I do two, I could not participate in any workshops other people lead?

Correct :)

>  Made up my mind. In any case I would be willing to lead both workshops...

Great :) I'll get both on the schedule.

**Comment by DJCordhose** [comment]
Perfect, please do :)

**Comment by kyoukhana** [comment]
This workshop sounds great.  I would be interested too see ReactJS in the mix minus the handlebars.  Most of the Ember Guys are moving towards HTMLBars.

**Comment by DJCordhose** [comment]
I agree that React is much more exciting, but also a tad more complex than handlebars. This is supposed to be a beginners tutorial and an hour is not a lot of time, so I would rather stick to handlebars. 

Maybe we could use the final iteration for the React variant, though?

**Comment by DJCordhose** [comment]
In any case, there will be a project on github you can fork to get started easily. 

Additionally, all server side JavaScript code will use ES6 syntax as natively supported by io.js.

If we use react client side code (optional), the same syntax is supported by react tools and can be translated to ES5.

**Comment by kyoukhana** [comment]
I agree with you keep it simple.

**Comment by DJCordhose** [comment]
Here is the seed for the workshop now

https://github.com/DJCordhose/iojs-web-seed

Maybe someone can try to install and run the whole thing as described in

https://github.com/DJCordhose/iojs-web-seed/blob/master/README.md#installation

**Comment by DJCordhose** [comment]
Groked some isomorphic rendering with Yahoo's Fluxible and react and created a very simple example: 

https://github.com/DJCordhose/react-playground/tree/master/code/fluxible-isomorphic

can also show this, if anyone is interested.

**Comment by mikeal** [comment]
awesome, FYI, we're probably going to be doing the workshops later in the day rather than at the beginning. we'll work out all the timing once we get to the camp and start building the schedule :)

**Comment by DJCordhose** [comment]
Sure, no worries, I am very flexible and like the spontaneous style :smile_cat:
