### ISSUE TITLE
program committee 

### ISSUE THREAD

**Issue by tamzinblake** [nodeconf/Adventure-UNCONF#30]
We don't have any talks to curate, but we need folks to organize the nodeschool workshops.

I might remember @maxogden saying he wanted to help in some capacity with that?

**Comment by tamzinblake** [comment]
We might want to see if we can acquire some extra computers from somewhere.

**Comment by mikeal** [comment]
If you're doing talks, have you thought about how/where they would be?

**Comment by tamzinblake** [comment]
No talks

**Comment by tamzinblake** [comment]
Removing this placeholder
