### ISSUE TITLE
volunteer team

### ISSUE THREAD

**Issue by tamzinblake** [nodeconf/Adventure-UNCONF#31]
We need someone to head up the volunteer team.

Pre-conference: handling stuff like acquiring awesome non-alcoholic beverages and renting the van.

During the conference: keeping people organized, answering questions, packing and unpacking stuff, fire safety.

**Comment by mikeal** [comment]
You might be able to get out of the van rental. Bevmo can delivery alcohol and I'm told Costco can deliver non-alcoholic.

**Comment by ryan-sandy** [comment]
I'd be happy to head the volunteer team.

**Comment by tamzinblake** [comment]
We probably don't need to solidify that stuff for a while yet.
