### ISSUE TITLE
Nodeschool organizer wanted

### ISSUE THREAD

**Issue by tamzinblake** [nodeconf/Adventure-UNCONF#34]
We were hoping to make Nodeschool a significant presence at NodeConf Adventure 2017, so it would be great if we could find a co-organizer for the unconf who has some experience running Nodeschool events. @maxogden might have some thoughts on who we should ask, particularly someone from an underrepresented group?

**Comment by nebrius** [comment]
@llkats, @jedireza would you be interested in helping us co-organize an extended NodeSchool event at the next NodeConf Adventure?

**Comment by tamzinblake** [comment]
FYI llkats is unavailable

**Comment by llkats** [comment]
I could tentatively be available to help run the session. For the next couple months, I want to focus on the new job that I'm starting, but perhaps starting mid-May would have the brainspace to help with logistics. I understand if you need a firm commitment or more involvement before then, though.

**Comment by tamzinblake** [comment]
@llkats Thanks! I'll keep you in mind if we haven't gotten this figured out yet when mid-May rolls around.

**Comment by jedireza** [comment]
Let me know how I can help.

**Comment by nebrius** [comment]
To give some context for this issue, a few of us were chatting about the future of NodeConf Adventure at the last event, and one of the things we discussed was the focus of the conference and how well it did/did not work for some folks.

NodeConf Adventure attracts an interesting set of folks. There are quite a few of us there who are involved in the Node project itself, and so some of the sessions end up being almost like a Node.js Foundation collaborator's summit, where we discuss some of the issues facing the Node project. Of course, this tends to involve a fair amount of insider baseball and so isn't very useful for people not involved. This isn't to say these discussions aren't helpful, a lot of good things have come out of NodeConf Adventure, such as some early ideas for [LTS](https://github.com/nodejs/LTS). That said, there are people who attend who aren't interested/don't have the background knowledge necessary to participate in these sessions.  There are sessions covering other topics that are broader, but many of us feel we're missing out on catering more to beginners.

There have also been workshops held at previous NodeConf Adventures that were popular. These tended to be rather one-off, and required organizing "from scratch."

An idea that a few of us kicked around was to work with NodeSchool to have something like a "super NodeSchool" that ran for much/all of the event, and perhaps had more directed workshops than a typical NodeSchool event.

What are your thoughts/opinions @jedireza and @llkats?

**Comment by mikeal** [comment]
> There have also been workshops held at previous NodeConf Adventures that were popular. These tended to be rather one-off, and required organizing "from scratch."

For two consecutive years NodeConf at Walker Creek was *entirely* workshops :)

One of the reasons I stopped doing it was that attendance was on a slight decline and the cost of doing a full slate of workshops was a lot more. There was maybe triple the organizing effort and each workshop had at least two people running them who needed their travel/lodging/food covered (which is the least you can do, it was a serious and tough job to run those workshops). All of that increased the base cost of the event which meant that it would lose money if it didn't get over a certain number of tickets sold which, at a certain point, was a risk I didn't want to take.

That said, doing something less formal, something that didn't require all the scheduling overhead and 20 workshop runners would still be well received. NodeSchool basically started the first time we did this and the next year we doubled the number of workshoppers in NodeSchool to a whopping eight workshops, so it's been a while and there is a lot more NodeSchool infrastructure and far more people skilled in running the workshops.

Just keep in mind that the more formal you make all of this the more organizing overhead necessary and, if you pull on this thread enough, you could also change the cost model.

**Comment by nebrius** [comment]
@mikeal That's pretty much exactly why we were thinking about doing an extended NodeSchool thing: low overhead :). Whatever this looks like, I agree that it should be as informal as we can make it.

I could see something like having 2-3 "full time" organizers/mentors, and maybe another 1-2 "full time" workshop leads that are formally designated (and travel/lodging/food covered), and everything else would be handled by mentors that come and go throughout the conference. We could maybe offer discounted tickets (10-20% off maybe?) in exchange for one morning or afternoon of mentoring. This should reduce the cost to the conference, allow mentors to still enjoy the rest of the conference, but still compensate mentors for their time.

**Comment by llkats** [comment]
Ah, I see. This context is really valuable -- I definitely thought you meant running one or two sessions as workshops, not the entire conference. That is out of the scope of the time I have to devote to volunteering in that capacity, I'm sorry to say. Thank you for the additional context and explanation!

**Comment by nebrius** [comment]
No worries @llkats, do what you need to do!

I should also add this is just one possibility. Maybe having sessions the entire time is too much? Maybe it would make sense to only hold them during the afternoons?

**Comment by tamzinblake** [comment]
I'm thinking we don't need to hold them the entire time. Also we probably don't need quite that much commitment. Note that we will also having some sort of Nodebots thing, and there's room for other stuff too.

**Comment by jedireza** [comment]
I don't see myself having the bandwidth to help organize. Thanks for reaching out to me. I look forward to hearing about your progress with NodeConf Adventure.
