### ISSUE TITLE
3 day event?

### ISSUE THREAD

**Issue by tamzinblake** [nodeconf/Adventure-UNCONF#35]
The website claims that Nodeconf is a 3-day event. I guess that's kind of true, since there are some activities on Friday, but nothing except food and leaving on Sunday. Still, it seems counterintuitive at least to say the event is 3 days and is July 6-9 (a 4-day span). Any thoughts?

**Comment by nebrius** [comment]
IIRC, in the past there has been dinner followed by socializing Friday night, so I guess you could argue that plus Sunday lunch equals three days?

I wouldn't find it strange to call it a two day event though, or we could also sidestep it by saying "NodeConf Adventure is a multi-day event for the whole family."

**Comment by tamzinblake** [comment]
Multi-day event - I like that.
