### ISSUE TITLE
Workshop Suggestion

### ISSUE THREAD

**Issue by kyoukhana** [nodeconf/Adventure-UNCONF#4]
How about a Workshop on Hapijs Firebase ReactJS.

**Comment by mikeal** [comment]
Is this a workshop you would be building the materials for and leading or just a suggestion for something someone else should do?

**Comment by kyoukhana** [comment]
I would love to do a workshop.  But right know my Knowledge of ReactJS is limited.  I might be able to get up to speed before the conference.  But to put a actual presentation or workshop not 100% sure.
