### ISSUE TITLE
Discussion: Hashes, Blockchains, and Merkle DAGs - oh my!

### ISSUE THREAD

**Issue by kumavis** [nodeconf/Adventure-UNCONF#5]
Hello! :smile_cat: 

Me and a friend @wanderer are working with a project called Ethereum.
Ethereum is based on bitcoin technology, but adds a turing complete language on top, turning the blockchain into a simple VM.
Ethereum is being implemented in a few different languages and @wanderer is writing the node client.
I am writing a front-end via browserify.

We're curious if we could talk about our work at nodeconf adventure. I think the project is an example of some of the audacious things you can do that people don't expect from javascript.

So lets address the primary reason one might say no: we don't want peeps coming in and just advertising their startup. fair enough. for full disclosure, here's some relevant facts, for and against:
- @wanderer is paid by the ethereum org to work on ethereum
- I work with ethereum independently
- we both have some financial investment in ethereum and stand to benefit from its adoption
- the Ethereum Foundation is a non-profit organization ( https://ethereum.org/foundation )
- ethereum is a crypto-asset that has not yet launched so we must assume its a scamcoin™
- this will be my third year at node-conf!

Let us know what you think. If a focus on a single project with financial contexts doesn't seem appropriate, we could additionally cover a few things (crypto, bitcoin, ipfs).

This could be a talk or a workshopper, though I would lean towards a talk. A workshopper could be successful depending on internet connectivity, as its a decentralized network.

**Comment by kumavis** [comment]
also re: workshopper vs discussion, I feel like the value here is more about expanding minds on what people can do with node.js and less about learning how to use ethereum itself.

**Comment by mikeal** [comment]
This sounds like a good "discussion" during the unconf.

**Comment by kumavis** [comment]
@wanderer moved to Europe, so I'll be juggling this one on my own.

**Comment by kumavis** [comment]
@mikeal 
Can you tell me more about the 'discussion' format?
will there be a projector?
mostly talking + QA?
