### ISSUE TITLE
Workshop: Cross platform with Atom Shell

### ISSUE THREAD

**Issue by bengotow** [nodeconf/Adventure-UNCONF#7]
For the last several months, me and my team at Nilas have been working on an email client built on top of Atom Shell. Atom Shell is a project from Github that bundles io.js and Chromium. It allows you to deliver cross-platform desktop applications written entirely in Javascript, with native menus, windows, integration with notification center, etc.

We've really enjoyed using it, and I think it'd be great to walk folks through the basics of creating a new Atom Shell app, opening windows and creating a quick UI with React.

Atom Shell is also being used for Slack's Windows app, Mapbox Studio, Github's Atom text editor, and more!

If enough other folks are using Atom Shell (or NW.js), we could also turn this into a discussion.

**Comment by mikeal** [comment]
Love it, I'll get it on the schedule, make sure you get a ticket :)

**Comment by wonderdogone** [comment]
:+1:

**Comment by sterlingwes** [comment]
:+1:

**Comment by eudaimos** [comment]
:+1:

**Comment by MaxZoosk** [comment]
Looking forward to this
