### ISSUE TITLE
Swimming & Naturalist Hikes

### ISSUE THREAD

**Issue by mikeal** [nodeconf/Adventure-UNCONF#9]
We have the pond from 2pm-5pm Thursday, Friday and Saturday.

If someone lets me know what they'd like to do naturalist hikes for the kids and significant others let me know.

**Comment by lyle** [comment]
@mikeal is there a naturalist hike leader that works at the ranch?

**Comment by mikeal** [comment]
We haven't gotten times to the naturalist yet so I don't know for certain that we'll be able to reserve one but if we have times that we think are good we can talk to the camp when we get there tomorrow.
